# Generated by Django 5.0.2 on 2024-02-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('quote', models.TextField()),
                ('author', models.CharField(max_length=255)),
            ],
        ),
    ]
